<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Shop;
use App\Models\ShopOrder;
use App\Models\ShopOrderItem;
use App\Models\User;
use App\Services\Purchasing\PurchaserBusinessDayService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ShopOrderTable20260731Seeder extends Seeder
{
    private const BUSINESS_DATE = '2026-07-31';

    private const ORDER_SOURCE = 'seeded_order_form_table_2026_07_31';

    private const ITEM_LINES = <<<'DATA'
1|Tomato H|AV_CASIO:20,AV_LULU_BUDHIGERE:15,AV_ASHIRWAD:10,AV_SANA_JP:10,AV_GM_MIDLAND:10,AV_FOOD_PALACE_HSR:15,AV_LULU_BEGUR:25,AV_JINDAL_CITY:40,DS_FORTUNE_SM:20
2|Tomato N|AV_LULU_BUDHIGERE:15,AV_ASHIRWAD:5,AV_GM_MIDLAND:10,AV_FOOD_PALACE_HSR:5,AV_LULU_BEGUR:20,AV_JINDAL_CITY:30
8|Sambar Onion|AV_GRANDCITY:2,AV_SANA_JP:2,AV_FOOD_PALACE_HSR:1
12|Carrot|AV_CASIO:10,AV_LULU_BUDHIGERE:12,AV_GRANDCITY:10,AV_ASHIRWAD:6,AV_SANA:5,AV_SANA_JP:6,AV_LULU_VARTHUR:15,AV_GM_MIDLAND:6,AV_FOOD_PALACE_HSR:8,AV_LULU_BEGUR:12,DS_FORTUNE_SM:10
13|French Beans|AV_CASIO:5,AV_LULU_BUDHIGERE:7,AV_GRANDCITY:5,AV_ASHIRWAD:6,AV_SANA_JP:2,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:6,AV_JINDAL_CITY:15,DS_FORTUNE_SM:5
15|ladies Finger|AV_CASIO:10,AV_LULU_BUDHIGERE:10,AV_GRANDCITY:5,AV_ASHIRWAD:2,AV_SANA:5,AV_LULU_VARTHUR:15,AV_GM_MIDLAND:2,AV_LULU_BEGUR:8,DS_FORTUNE_SM:10
16|Green Peas|AV_LULU_BUDHIGERE:1,AV_GRANDCITY:2.5,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2.5,AV_JINDAL_CITY:3,DS_FORTUNE_SM:1
17|Broad beans S / Belt|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:2,AV_ASHIRWAD:1,AV_SANA:1,AV_SANA_JP:1.5,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2,DS_FORTUNE_SM:2
18|Paper Chikkdi|AV_LULU_BUDHIGERE:1,AV_GRANDCITY:2,AV_ASHIRWAD:1,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_FOOD_PALACE_HSR:1
20|Green Karamani|AV_LULU_BUDHIGERE:1,AV_SANA:2,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,DS_FORTUNE_SM:2
22|Cluster Beans / Gorikkai|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1.5,AV_SANA:1,AV_LULU_VARTHUR:2,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:1.5,DS_FORTUNE_SM:1
23|Green Chilli Normal|AV_GRANDCITY:2.5,AV_ASHIRWAD:1,AV_SANA:2,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_JINDAL_CITY:5
24|Chilli Spicy / Akash G4|AV_CASIO:2.5,AV_LULU_BUDHIGERE:2,AV_ASHIRWAD:1,AV_SANA:3,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:4,AV_JINDAL_CITY:5
25|Bajji Chilli|AV_CASIO:2.5,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1
27|Brinjal White Long|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1,AV_SANA:1,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:1
28|Brinjal Big (Bertha)|AV_CASIO:2,AV_LULU_BUDHIGERE:2,AV_SANA:3,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:6,DS_FORTUNE_SM:8
29|Brinjal Small|AV_LULU_BUDHIGERE:2,AV_ASHIRWAD:1.5,AV_SANA:1,AV_SANA_JP:1,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:1.5,DS_FORTUNE_SM:2
30|Brinjal White Kolkata|AV_LULU_BUDHIGERE:2,AV_SANA:3,DS_FORTUNE_SM:1
31|Brinjol Rampuri|AV_LULU_BUDHIGERE:1.5,AV_ASHIRWAD:1,AV_SANA:1,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:2,AV_LULU_BEGUR:1
32|Brinjal Blue Long|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1,AV_ASHIRWAD:1,AV_SANA:1,AV_LULU_VARTHUR:2
33|Capsicum|AV_CASIO:4,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2.5,AV_ASHIRWAD:2.5,AV_SANA:2,AV_SANA_JP:2,AV_LULU_VARTHUR:5,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:4,AV_LULU_BEGUR:5
34|Beetroot Ootty|AV_CASIO:4,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:4,AV_ASHIRWAD:3,AV_SANA:3,AV_SANA_JP:2,AV_LULU_VARTHUR:6,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:5,DS_FORTUNE_SM:5
35|Chow Chow|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:2.4,AV_ASHIRWAD:2,AV_SANA:2.5,AV_SANA_JP:1,AV_LULU_VARTHUR:1,AV_FOOD_PALACE_HSR:1.5
36|Noolkol (Kohlrbi)|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1,AV_ASHIRWAD:1,AV_SANA_JP:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:2
37|Radish|AV_CASIO:3,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:4,AV_SANA:3,AV_SANA_JP:2,AV_LULU_VARTHUR:6,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:4,DS_FORTUNE_SM:5
38|Tinda (Round Gurad)|AV_CASIO:1,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2,AV_SANA:2,AV_SANA_JP:1,AV_LULU_VARTHUR:3,AV_FOOD_PALACE_HSR:1
39|Bitter Gourd Big|AV_CASIO:2,AV_LULU_BUDHIGERE:1.5,AV_GRANDCITY:2,AV_ASHIRWAD:1,AV_SANA:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1,DS_FORTUNE_SM:2
40|Bitter Gourd Small|AV_CASIO:1.5,AV_LULU_BUDHIGERE:3,AV_GRANDCITY:2,AV_ASHIRWAD:1,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2,DS_FORTUNE_SM:1
41|Bitter Gourd White|DS_FORTUNE_SM:1
42|Bottle Gourd (Loki)|AV_CASIO:5,AV_LULU_BUDHIGERE:6,AV_GRANDCITY:5,AV_ASHIRWAD:2,AV_SANA:3,AV_SANA_JP:5,AV_LULU_VARTHUR:10,AV_GM_MIDLAND:3,AV_LULU_BEGUR:15
43|Ridge Gourd|AV_CASIO:4,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:3,AV_ASHIRWAD:2,AV_SANA:5,AV_SANA_JP:3,AV_LULU_VARTHUR:10,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:5
44|Drum Stick|AV_CASIO:2,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:2,AV_ASHIRWAD:1,AV_SANA:2,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:1.5,AV_LULU_BEGUR:2
45|Snake Gourd White|AV_GRANDCITY:2,AV_GM_MIDLAND:1,AV_LULU_BEGUR:1.5,DS_FORTUNE_SM:1
48|Banana Flower|AV_SANA:5,DS_FORTUNE_SM:3
49|Banana Stem|AV_SANA:5,AV_FOOD_PALACE_HSR:4
50|Raw Banana|AV_CASIO:10,AV_LULU_BUDHIGERE:6,AV_GRANDCITY:10,AV_ASHIRWAD:6,AV_SANA:12,AV_SANA_JP:6,AV_LULU_VARTHUR:12,AV_GM_MIDLAND:6,AV_FOOD_PALACE_HSR:10,DS_FORTUNE_SM:12
52|Sambar Cucbr / Southikai|AV_SANA_JP:2
53|Cucumber|AV_CASIO:10,AV_LULU_BUDHIGERE:11,AV_GRANDCITY:15,AV_ASHIRWAD:8,AV_SANA:10,AV_SANA_JP:8,AV_LULU_VARTHUR:10,AV_GM_MIDLAND:8,AV_FOOD_PALACE_HSR:5,AV_LULU_BEGUR:10,AV_JINDAL_CITY:50
54|English Cucumber|AV_LULU_BUDHIGERE:3,AV_GRANDCITY:2.5,AV_ASHIRWAD:1,AV_SANA:3,AV_SANA_JP:2,AV_LULU_VARTHUR:6,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:5
57|Raw Mango Gund|AV_LULU_VARTHUR:1,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2,AV_JINDAL_CITY:3,DS_FORTUNE_SM:2
58|Raw Mango totapuri|AV_GRANDCITY:2.5,AV_JINDAL_CITY:3
59|Lemon|AV_CASIO:3,AV_LULU_BUDHIGERE:3,AV_GRANDCITY:2,AV_ASHIRWAD:2,AV_SANA:3,AV_SANA_JP:2,AV_LULU_VARTHUR:5,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:4,AV_JINDAL_CITY:6,DS_FORTUNE_SM:5
60|Cauliflower|AV_CASIO:8,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:8,AV_ASHIRWAD:4,AV_SANA:5,AV_SANA_JP:5,AV_LULU_VARTHUR:18,AV_GM_MIDLAND:6,AV_FOOD_PALACE_HSR:5,AV_LULU_BEGUR:15
61|Cabbage|AV_CASIO:5,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:3,AV_ASHIRWAD:3,AV_SANA:10,AV_SANA_JP:3,AV_LULU_VARTHUR:6,AV_GM_MIDLAND:5,AV_FOOD_PALACE_HSR:5,AV_LULU_BEGUR:8
62|Arbi /Taroroot|AV_CASIO:1,AV_GRANDCITY:2,AV_ASHIRWAD:2,AV_LULU_VARTHUR:2,DS_FORTUNE_SM:2
63|Big Arbi|DS_FORTUNE_SM:2
65|Amla|AV_ASHIRWAD:1,AV_SANA:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1
67|Jack Fruit Ripe|AV_CASIO:2,AV_LULU_BUDHIGERE:2,AV_ASHIRWAD:1,AV_SANA:5,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:2
69|Raw Turmeric Kalkata|AV_GM_MIDLAND:2
70|Delhi / Red Carrot|DS_FORTUNE_SM:10
71|Kovakka Normal|AV_CASIO:2,AV_LULU_BUDHIGERE:2,AV_ASHIRWAD:1,AV_LULU_VARTHUR:3,AV_FOOD_PALACE_HSR:2,DS_FORTUNE_SM:2
72|Parval / Potol|AV_CASIO:1,AV_LULU_BUDHIGERE:3,AV_SANA:3,AV_LULU_VARTHUR:4,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:3,DS_FORTUNE_SM:3
73|Sweet Potato|AV_LULU_BUDHIGERE:2,AV_GRANDCITY:3,AV_ASHIRWAD:1.5,AV_SANA:3,AV_LULU_VARTHUR:3,AV_LULU_BEGUR:3,AV_JINDAL_CITY:5,DS_FORTUNE_SM:3
74|Tapioca|AV_SANA:3,DS_FORTUNE_SM:10
75|Ginger|AV_CASIO:3,AV_LULU_BUDHIGERE:5,AV_GRANDCITY:2,AV_ASHIRWAD:1.5,AV_SANA:3,AV_SANA_JP:2,AV_LULU_VARTHUR:5,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:4
76|Ground Nut|AV_GM_MIDLAND:4,AV_JINDAL_CITY:3,DS_FORTUNE_SM:2
77|Round Lauki White|AV_SANA:5
79|Raw Pappaya|AV_SANA:3,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:2
80|SP Natti Thondakai|AV_LULU_BUDHIGERE:1,AV_SANA:2,AV_LULU_VARTHUR:3,AV_LULU_BEGUR:2
81|Armenian Cucumber / Kakdi|AV_CASIO:1,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1,DS_FORTUNE_SM:1
83|White Pumkin|AV_CASIO:3,AV_LULU_VARTHUR:2,AV_LULU_BEGUR:3,DS_FORTUNE_SM:3
84|Yellow Pumkin|AV_CASIO:3,AV_LULU_BUDHIGERE:5,AV_ASHIRWAD:2,AV_LULU_VARTHUR:4,AV_LULU_BEGUR:4,AV_JINDAL_CITY:3
86|Turnip / Shalgam|AV_LULU_VARTHUR:2,DS_FORTUNE_SM:1
87|Mango Ginger|AV_CASIO:1
90|Flower K|AV_LULU_BUDHIGERE:1
91|kakrol / Kantola|AV_CASIO:1,AV_LULU_BUDHIGERE:1.5,AV_GRANDCITY:1,AV_ASHIRWAD:1,AV_SANA:2,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:2,DS_FORTUNE_SM:1
93|Lotus Stump|AV_CASIO:2,AV_LULU_BUDHIGERE:2,AV_LULU_VARTHUR:2
95|Singada|DS_FORTUNE_SM:2
96|Nenua gourd|AV_CASIO:1,AV_LULU_BUDHIGERE:3,AV_GRANDCITY:2,AV_SANA:2,AV_LULU_VARTHUR:8,AV_LULU_BEGUR:3,AV_JINDAL_CITY:3,DS_FORTUNE_SM:2
101|Corriander|AV_CASIO:10,AV_LULU_BUDHIGERE:15,AV_GRANDCITY:10,AV_ASHIRWAD:6,AV_SANA:12,AV_SANA_JP:7,AV_LULU_VARTHUR:15,AV_GM_MIDLAND:7,AV_FOOD_PALACE_HSR:10,AV_LULU_BEGUR:12,DS_FORTUNE_SM:20
102|Corriander Natti|AV_LULU_BUDHIGERE:4,AV_GRANDCITY:3,AV_GM_MIDLAND:1
103|Curry Leaf|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:0.5,AV_ASHIRWAD:0.5,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:0.5,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:1,DS_FORTUNE_SM:1
104|Pudina / Mint Leaf|AV_CASIO:5,AV_LULU_BUDHIGERE:8,AV_GRANDCITY:8,AV_ASHIRWAD:6,AV_SANA_JP:5,AV_LULU_VARTHUR:10,AV_GM_MIDLAND:6,AV_FOOD_PALACE_HSR:6,AV_LULU_BEGUR:5,DS_FORTUNE_SM:15
105|Palak|AV_CASIO:7,AV_LULU_BUDHIGERE:15,AV_GRANDCITY:10,AV_ASHIRWAD:5,AV_SANA:10,AV_SANA_JP:8,AV_LULU_VARTHUR:15,AV_GM_MIDLAND:5,AV_FOOD_PALACE_HSR:8,AV_LULU_BEGUR:10,DS_FORTUNE_SM:10
106|Green Cheera|AV_CASIO:1,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2,AV_SANA:1,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_LULU_BEGUR:2
107|Red Cheera|AV_CASIO:1,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2,AV_SANA:1,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:2,DS_FORTUNE_SM:3
108|Methi / Menthaya|AV_CASIO:5,AV_LULU_BUDHIGERE:10,AV_GRANDCITY:8,AV_ASHIRWAD:3,AV_SANA:3,AV_SANA_JP:5,AV_LULU_VARTHUR:12,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:8,DS_FORTUNE_SM:5
109|Spring Onion|AV_CASIO:1,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2,AV_ASHIRWAD:2,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,DS_FORTUNE_SM:2
110|Gongura|AV_LULU_BUDHIGERE:1,AV_SANA:2,AV_LULU_VARTHUR:1,DS_FORTUNE_SM:2
111|Basella leaf / Basala|AV_LULU_BUDHIGERE:1,DS_FORTUNE_SM:3
112|Sabbakki / Dil Leaf|AV_LULU_BUDHIGERE:1,AV_ASHIRWAD:1,AV_LULU_VARTHUR:2,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:1,DS_FORTUNE_SM:2
113|Chakotha|AV_LULU_BUDHIGERE:1,AV_LULU_VARTHUR:2
114|Mustard Leaf|AV_LULU_BUDHIGERE:1
115|Drum Stick Leaf|AV_LULU_BUDHIGERE:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:3,AV_LULU_BEGUR:2,DS_FORTUNE_SM:3
116|Arai Keerai|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_SANA:1,AV_SANA_JP:1,AV_GM_MIDLAND:2,AV_LULU_BEGUR:2
117|Siru Keerai|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_SANA:1,AV_SANA_JP:1,AV_GM_MIDLAND:1,AV_LULU_BEGUR:2
120|Sweet Corn|AV_CASIO:5,AV_LULU_BUDHIGERE:8,AV_GRANDCITY:5,AV_ASHIRWAD:4,AV_SANA:15,AV_SANA_JP:10,AV_LULU_VARTHUR:8,AV_GM_MIDLAND:8,AV_FOOD_PALACE_HSR:6,AV_LULU_BEGUR:10
121|Peeled Corn|AV_CASIO:1,AV_SANA_JP:2,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:2
122|Baby Corn|AV_CASIO:1,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:3,AV_SANA_JP:2,AV_LULU_VARTHUR:1,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2
123|Peeled Garlic|AV_CASIO:2,AV_SANA:2,AV_SANA_JP:2,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:2,DS_FORTUNE_SM:2
124|Peeled Onion|AV_CASIO:1,AV_SANA:2,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:3
125|Cherry Tomato Box SP|AV_LULU_BEGUR:3
128|Mushroom|AV_CASIO:5,AV_LULU_BUDHIGERE:10,AV_GRANDCITY:8,AV_ASHIRWAD:5,AV_SANA:10,AV_SANA_JP:8,AV_LULU_VARTHUR:20,AV_GM_MIDLAND:10,AV_FOOD_PALACE_HSR:10,AV_LULU_BEGUR:10,DS_FORTUNE_SM:15
130|Broccoli|AV_CASIO:2.5,AV_LULU_BUDHIGERE:2,AV_GRANDCITY:2,AV_SANA:2,AV_SANA_JP:2,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:3,AV_JINDAL_CITY:3
133|Lettuce|AV_CASIO:0.25,AV_LULU_BUDHIGERE:0.25,AV_ASHIRWAD:0.5,AV_SANA:0.25,AV_LULU_VARTHUR:0.2,AV_FOOD_PALACE_HSR:0.5
134|Ice Berg Lettuce|AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:1
135|Colur Capcicum Yellow|AV_CASIO:1,AV_LULU_BUDHIGERE:0.5,AV_SANA:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1,DS_FORTUNE_SM:1
136|Colur Capcicum Red|AV_CASIO:1,AV_LULU_BUDHIGERE:0.5,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_FOOD_PALACE_HSR:1,DS_FORTUNE_SM:1
137|Zuchini Green|AV_ASHIRWAD:0.5,AV_LULU_VARTHUR:1
138|Zuchini Yellow|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1
139|Red Cabbage|AV_ASHIRWAD:1
141|Celery Leaf|AV_SANA:0.25,AV_LULU_VARTHUR:0.2
143|Basaley Leaf|AV_SANA:0.25
146|Sprouds Mix|AV_LULU_BUDHIGERE:3,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:2
147|Sprouds Green Gram|AV_CASIO:2,AV_GM_MIDLAND:2
151|Bel (Kolkata Item)|DS_FORTUNE_SM:3
153|Kolkata Lemon|AV_CASIO:1,AV_LULU_BUDHIGERE:1
154|Kochu Loti|AV_LULU_BUDHIGERE:1,DS_FORTUNE_SM:3
156|Maankochoo|AV_LULU_BUDHIGERE:1,DS_FORTUNE_SM:6
162|Banana yelakki Green|AV_CASIO:2,AV_LULU_BUDHIGERE:3,AV_ASHIRWAD:2,AV_SANA:2,AV_SANA_JP:1,AV_LULU_VARTHUR:2,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:3,DS_FORTUNE_SM:3
163|Banana Yelakki Color|AV_SANA:1,AV_FOOD_PALACE_HSR:1
164|Banana Nendran|AV_CASIO:1,AV_LULU_BUDHIGERE:1,AV_ASHIRWAD:1,AV_SANA:1,AV_GM_MIDLAND:1,AV_LULU_BEGUR:1,DS_FORTUNE_SM:1
166|Banana Robusta|AV_CASIO:15,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1,AV_ASHIRWAD:15,AV_SANA:25,AV_SANA_JP:10,AV_LULU_VARTHUR:30,AV_GM_MIDLAND:15,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:25,DS_FORTUNE_SM:1
181|Pappaya|AV_CASIO:15,AV_LULU_BUDHIGERE:20,AV_GRANDCITY:20,AV_ASHIRWAD:8,AV_SANA:15,AV_SANA_JP:10,AV_LULU_VARTHUR:35,AV_GM_MIDLAND:5,AV_FOOD_PALACE_HSR:10,AV_LULU_BEGUR:20
3|Onion|AV_CASIO:15,AV_LULU_BUDHIGERE:50,AV_GRANDCITY:50,AV_SANA_JP:25,AV_LULU_VARTHUR:50,AV_GM_MIDLAND:50,AV_FOOD_PALACE_HSR:50,AV_LULU_BEGUR:50
4|Pickle Onion Bag|AV_SANA:2,AV_GM_MIDLAND:3,DS_FORTUNE_SM:3
5|Potato Agra|AV_LULU_BUDHIGERE:25,AV_GRANDCITY:25,AV_FOOD_PALACE_HSR:25,AV_JINDAL_CITY:50
6|Potato Local|AV_CASIO:20,AV_LULU_VARTHUR:25,AV_LULU_BEGUR:50,DS_FORTUNE_SM:2
7|Baby Potato|AV_GRANDCITY:3
9|Onion White|AV_GM_MIDLAND:1
10|Garlic Natti|AV_GM_MIDLAND:5
11|Garlic Ootty|AV_CASIO:2,AV_SANA:3,AV_SANA_JP:2,AV_FOOD_PALACE_HSR:3,AV_LULU_BEGUR:3,AV_JINDAL_CITY:4
170|Coconut|AV_CASIO:10,AV_LULU_BUDHIGERE:15,AV_GRANDCITY:10,AV_SANA:15,AV_SANA_JP:20,AV_GM_MIDLAND:6,AV_FOOD_PALACE_HSR:15,AV_LULU_BEGUR:15,AV_JINDAL_CITY:30
182|Gala NZ|AV_LULU_BUDHIGERE:0.5,AV_GRANDCITY:0.5,AV_ASHIRWAD:0.5
183|Gala Apple|AV_SANA:0.5,AV_LULU_VARTHUR:0.5,AV_LULU_BEGUR:1,AV_JINDAL_CITY:0.5
187|Apple Pink lady|AV_LULU_BUDHIGERE:0.5,AV_SANA_JP:0.5
188|Red Apple|AV_CASIO:1
191|Rockit Apple|AV_LULU_BUDHIGERE:1,AV_SANA:1,AV_JINDAL_CITY:1
192|Washington Apple|AV_FOOD_PALACE_HSR:0.5
193|Mini Orange|AV_GRANDCITY:1,AV_LULU_VARTHUR:0.5,AV_GM_MIDLAND:1,AV_JINDAL_CITY:0.5
194|Mini Orange SL|AV_CASIO:0.5,AV_FOOD_PALACE_HSR:0.5
195|Pears|AV_CASIO:0.25,AV_LULU_BUDHIGERE:0.25,AV_ASHIRWAD:0.2,AV_SANA:0.5,AV_LULU_VARTHUR:0.5,AV_GM_MIDLAND:0.25,AV_JINDAL_CITY:0.5
196|Citrus Orange|AV_CASIO:1,AV_GRANDCITY:0.5
198|Dragon Fruit|AV_GRANDCITY:3
199|Red Dragon|AV_GRANDCITY:2.5,AV_SANA:3,AV_SANA_JP:3,AV_LULU_VARTHUR:2
200|Kiwi|AV_GRANDCITY:5,AV_GM_MIDLAND:2,AV_FOOD_PALACE_HSR:2,AV_LULU_BEGUR:3,AV_JINDAL_CITY:8
201|Golden Kiwi|AV_CASIO:3,AV_FOOD_PALACE_HSR:2
204|Redglobe|AV_SANA:1,AV_JINDAL_CITY:1
205|Redglobe SL|AV_GM_MIDLAND:1
210|Blue Berry|AV_LULU_BUDHIGERE:3,AV_GRANDCITY:2,AV_LULU_VARTHUR:6,AV_LULU_BEGUR:4,AV_JINDAL_CITY:3
213|Bare Apple|AV_JINDAL_CITY:1
215|Golden Custard|AV_GM_MIDLAND:5,AV_FOOD_PALACE_HSR:3
217|Watermelon|AV_GRANDCITY:1,AV_LULU_BEGUR:1
221|Pineapple|AV_GRANDCITY:5,AV_ASHIRWAD:3,AV_SANA:3,AV_SANA_JP:3,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:2,AV_JINDAL_CITY:8
223|Musambi|AV_CASIO:3,AV_LULU_BUDHIGERE:3,AV_SANA:3,AV_LULU_VARTHUR:3,AV_GM_MIDLAND:3,AV_LULU_BEGUR:3
224|Anar / Pomegranate|AV_LULU_VARTHUR:1,AV_GM_MIDLAND:1,AV_FOOD_PALACE_HSR:1,AV_LULU_BEGUR:1
227|Supporta / Chikoo|AV_LULU_BUDHIGERE:3,AV_GRANDCITY:4,AV_SANA:3
228|Thai Guava|AV_CASIO:5,AV_LULU_BUDHIGERE:10,AV_GRANDCITY:5,AV_ASHIRWAD:2,AV_SANA:5,AV_SANA_JP:3,AV_LULU_VARTHUR:10,AV_GM_MIDLAND:3,AV_FOOD_PALACE_HSR:5,AV_LULU_BEGUR:10,AV_JINDAL_CITY:20,DS_FORTUNE_SM:10
230|Muskmelon|AV_LULU_BUDHIGERE:5,AV_SANA_JP:3,AV_JINDAL_CITY:5
231|Patta Jam|AV_LULU_BUDHIGERE:5,AV_GRANDCITY:12,AV_LULU_VARTHUR:10,AV_JINDAL_CITY:10
235|Butter Fruit|AV_CASIO:3,AV_SANA:3,AV_LULU_VARTHUR:3
238|Rambutan|AV_LULU_BEGUR:3
242|Mangosteen|AV_LULU_VARTHUR:3,AV_LULU_BEGUR:3
244|Mango BP|AV_LULU_BUDHIGERE:1,AV_LULU_VARTHUR:1
254|Mango Neelam|AV_GRANDCITY:1,AV_ASHIRWAD:0.5,AV_SANA:1,AV_SANA_JP:1,AV_LULU_VARTHUR:1,AV_GM_MIDLAND:20,AV_FOOD_PALACE_HSR:0.5,AV_LULU_BEGUR:25,AV_JINDAL_CITY:1
256|Mango Langada|AV_CASIO:2,AV_LULU_BUDHIGERE:1,AV_GRANDCITY:1,AV_LULU_VARTHUR:2,DS_FORTUNE_SM:3
300|Plate 1d|AV_ASHIRWAD:1
301|Plate 2D|AV_CASIO:1,AV_JINDAL_CITY:1
302|Wrapping Roll|AV_LULU_BEGUR:1,AV_JINDAL_CITY:1
305|Papper Bag 1kg|AV_GM_MIDLAND:3
306|Papper Bag 3kg|AV_ASHIRWAD:2,AV_LULU_VARTHUR:10
309|Cover 16X20|AV_SANA_JP:1
312|Billing Roll|AV_LULU_BEGUR:10
DATA;

    public function run(): void
    {
        $businessDate = Carbon::parse(self::BUSINESS_DATE);
        $submittedDate = $businessDate->copy()->subDay();
        $deadlineAt = app(PurchaserBusinessDayService::class)->rolloverStartsAt($submittedDate);
        $reviewer = User::role('purchase')->first() ?? User::role('admin')->first() ?? User::query()->first();

        if (! $reviewer instanceof User) {
            $this->command?->warn('ShopOrderTable20260731Seeder skipped: no user available.');

            return;
        }

        DB::transaction(function () use ($businessDate, $submittedDate, $deadlineAt, $reviewer): void {
            $shopsByCode = Shop::query()->active()->get()->keyBy('code');
            $productsBySku = Product::query()->active()->get()->keyBy('sku');
            $itemsByShop = $this->itemsByShop();
            $createdOrders = 0;
            $createdItems = 0;
            $missingShops = [];
            $missingProducts = [];

            foreach ($itemsByShop as $shopCode => $items) {
                $shop = $shopsByCode->get($shopCode);

                if (! $shop instanceof Shop) {
                    $missingShops[] = $shopCode;

                    continue;
                }

                $creator = User::role('shop')->where('shop_id', $shop->id)->first()
                    ?? $shop->users()->first()
                    ?? $reviewer;

                $order = ShopOrder::query()->updateOrCreate(
                    ['shop_daily_order_key' => $this->dailyOrderKey($shopCode, $businessDate)],
                    [
                        'shop_id' => $shop->id,
                        'order_source' => self::ORDER_SOURCE,
                        'state' => 'approved',
                        'delivery_status' => 'pending_delivery',
                        'delivery_review_status' => 'not_started',
                        'payment_status' => 'unpaid',
                        'business_date' => $businessDate->toDateString(),
                        'submitted_at' => $submittedDate->copy()->setTime(19, 0),
                        'deadline_at' => $deadlineAt,
                        'created_by' => $creator->id,
                        'reviewed_by' => $reviewer->id,
                        'reviewed_at' => $businessDate->copy()->setTime(8, 0),
                        'manager_note' => 'Seeded from niyas.xlsx for business date 2026-07-31.',
                        'is_late' => false,
                    ],
                );

                $order->items()->delete();
                $createdOrders++;

                foreach ($items as $itemData) {
                    $product = $productsBySku->get($itemData['product_sku']);

                    if (! $product instanceof Product) {
                        $missingProducts[] = $itemData['product_sku'];

                        continue;
                    }

                    ShopOrderItem::query()->create([
                        'shop_order_id' => $order->id,
                        'product_id' => $product->id,
                        'product_grade' => 'A',
                        'requested_qty' => $itemData['quantity'],
                        'approved_qty' => $itemData['quantity'],
                        'unit' => $product->unit,
                        'requested_unit' => $product->unit,
                        'requested_unit_label' => strtoupper((string) $product->unit),
                        'requested_unit_quantity' => $itemData['quantity'],
                        'requested_unit_conversion_to_base' => 1,
                        'locked_selling_price' => 0,
                        'locked_price_source' => 'table_seed',
                        'line_total' => 0,
                        'fulfillment_type' => 'warehouse',
                        'sorting_status' => 'pending',
                        'notes' => 'Seeded from niyas.xlsx for business date 2026-07-31.',
                    ]);

                    $createdItems++;
                }
            }

            if ($missingShops !== []) {
                $this->command?->warn('Missing shops: '.implode(', ', array_unique($missingShops)));
            }

            if ($missingProducts !== []) {
                $this->command?->warn('Missing products: '.implode(', ', array_unique($missingProducts)));
            }

            $this->command?->info(sprintf(
                'Seeded %d approved shop orders with %d items for %s.',
                $createdOrders,
                $createdItems,
                self::BUSINESS_DATE,
            ));
        });
    }

    /**
     * @return array<string, array<int, array{product_sku: string, quantity: float}>>
     */
    private function itemsByShop(): array
    {
        $itemsByShop = [];

        foreach (preg_split('/\r\n|\r|\n/', trim(self::ITEM_LINES)) as $line) {
            if (! $line) {
                continue;
            }

            [$sku, , $shopQuantities] = explode('|', $line, 3);

            foreach (explode(',', $shopQuantities) as $shopQuantity) {
                [$shopCode, $quantity] = explode(':', $shopQuantity, 2);
                $itemsByShop[$shopCode][] = [
                    'product_sku' => $sku,
                    'quantity' => (float) $quantity,
                ];
            }
        }

        return $itemsByShop;
    }

    private function dailyOrderKey(string $shopCode, Carbon $businessDate): string
    {
        return sprintf('table-shop-demand:%s:%s', $shopCode, $businessDate->toDateString());
    }
}
