@extends('admin.cashbook.layouts.app')
@section('title', 'Changed Items - Cashbook')
@section('header_title')
    <i data-lucide="arrow-left-right" class="h-5 w-5 text-emerald-600"></i> Changed Items
@endsection
@section('header_subtitle')
    Approved selling-price changes only.
@endsection
@section('content')
<div class="mx-auto max-w-[96rem] space-y-5">
    @include('admin.cashbook.finance.purchase.reports._header', ['reportName' => 'Changed Items', 'reportDescription' => 'Only approved selling prices that differ between the selected dates.'])
    @include('admin.cashbook.finance.purchase.reports._comparison-filters', ['filterRoute' => 'admin.cashbook.finance.purchase.reports.changed-items', 'showPriceGroup' => true])
    <div class="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><span class="text-[10px] font-black uppercase text-slate-400">Changed Items</span><strong class="mt-1 block font-mono text-xl text-slate-950">{{ number_format($rows->total()) }}</strong><p class="text-xs font-semibold text-slate-500">Group {{ $filters['price_group'] }} / {{ $filters['date_a'] }} to {{ $filters['date_b'] }}</p></div><a href="{{ route('admin.cashbook.finance.purchase.reports.changed-items.whatsapp', request()->query()) }}" target="_blank" rel="noopener" class="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-lg bg-emerald-700 px-4 text-xs font-black text-white"><i data-lucide="message-circle" class="h-4 w-4"></i> Share Changed Items</a></div>
    <section class="rounded-lg border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[48rem] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="p-3">Product</th><th class="p-3 text-right">{{ $filters['date_a'] }}</th><th class="p-3 text-right">{{ $filters['date_b'] }}</th><th class="p-3 text-right">Change</th><th class="p-3 text-right">Change %</th><th class="p-3 text-center">Direction</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($rows as $row)@php($change = (float) $row->current_price - (float) $row->previous_price)@php($percent = (float) $row->previous_price !== 0.0 ? $change / (float) $row->previous_price * 100 : null)<tr><td class="p-3 font-black text-slate-900">{{ $row->product_name }}<div class="text-[10px] font-semibold text-slate-400">{{ $row->category_name }} / {{ strtoupper($row->price_unit ?: $row->product_unit) }}</div></td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->previous_price, 2) }}</td><td class="p-3 text-right font-mono font-bold">₹{{ number_format((float) $row->current_price, 2) }}</td><td class="p-3 text-right font-mono font-bold {{ $change > 0 ? 'text-rose-700' : 'text-emerald-700' }}">{{ $change > 0 ? '+' : '' }}₹{{ number_format($change, 2) }}</td><td class="p-3 text-right font-mono">{{ $percent !== null ? ($percent > 0 ? '+' : '').number_format($percent, 2).'%' : '—' }}</td><td class="p-3 text-center"><i data-lucide="{{ $change > 0 ? 'arrow-up' : 'arrow-down' }}" class="mx-auto h-4 w-4 {{ $change > 0 ? 'text-rose-600' : 'text-emerald-600' }}"></i></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-400">No changed approved selling prices.</td></tr>@endforelse</tbody></table></div>@if($rows->hasPages())<div class="border-t border-slate-200 p-4">{{ $rows->links() }}</div>@endif</section>
</div>
@endsection
