<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Catalog — Green Leaf Traders</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        @media print {
            @page {
                size: A4 portrait;
                margin: 8mm 10mm;
            }
            body {
                background-color: #ffffff !important;
                color: #000000 !important;
                margin: 0 !important;
                padding: 0 !important;
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
            }
            .no-print {
                display: none !important;
            }
            .a4-print-card {
                border: 1px solid #cbd5e1 !important;
                box-shadow: none !important;
                max-width: 100% !important;
                width: 100% !important;
                margin: 0 auto !important;
                padding: 1.25rem 1.75rem !important;
            }
            .category-block {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body class="bg-slate-100 py-6 text-slate-950">
    <div class="no-print mx-auto mb-4 flex max-w-5xl items-center justify-between px-4">
        <a href="{{ route('inventory.products.index', request()->only(['search', 'category_id', 'status', 'unit'])) }}"
           class="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-xs font-bold text-slate-700 shadow-sm transition-colors hover:bg-slate-50">
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to Products
        </a>

        <div class="flex items-center gap-3">
            <span class="text-xs font-bold text-slate-500">{{ $products->count() }} product(s)</span>
            <button type="button" onclick="window.print()"
                    class="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-2 text-xs font-bold text-white shadow transition-colors hover:bg-emerald-700">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m11.32-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231a1.125 1.125 0 01-1.12-1.227L6.34 18m11.32 0H6.34" />
                </svg>
                Print / Save PDF
            </button>
        </div>
    </div>

    <main class="a4-print-card mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-8 shadow-md">
        <header class="flex items-start justify-between border-b border-slate-200 pb-5">
            <div>
                <p class="text-[11px] font-black uppercase tracking-[0.25em] text-emerald-700">Green Leaf Traders</p>
                <h1 class="mt-1 text-2xl font-black tracking-tight text-slate-900">Product Catalog</h1>
                <p class="mt-1 text-xs font-semibold text-slate-500">Category-wise inventory list with product codes</p>
            </div>
            <div class="text-right">
                <p class="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Generated Date</p>
                <p class="mt-1 text-xs font-bold text-slate-800">{{ now()->format('d M Y, h:i A') }}</p>
                <p class="mt-1 text-[11px] font-semibold text-slate-500">Generated by: {{ auth()->user()?->name ?? 'System' }}</p>
            </div>
        </header>

        <section class="mt-4 grid grid-cols-3 gap-4 rounded-xl border border-slate-100 bg-slate-50 p-4">
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Categories</p>
                <p class="mt-0.5 text-lg font-black text-slate-900">{{ $groupedProducts->count() }}</p>
            </div>
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Products</p>
                <p class="mt-0.5 text-lg font-black text-emerald-700">{{ number_format($products->count()) }}</p>
            </div>
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Active</p>
                <p class="mt-0.5 text-lg font-black text-slate-900">{{ $products->where('is_active', true)->count() }} / {{ $products->count() }}</p>
            </div>
        </section>

        @if(!empty($filters))
            <section class="mt-3 rounded-xl border border-slate-100 px-4 py-3 text-[11px] font-bold text-slate-500">
                Filters:
                @foreach($filters as $key => $value)
                    <span class="ml-2 inline-flex rounded-full bg-slate-100 px-2 py-0.5 text-slate-700">{{ str_replace('_', ' ', $key) }}: {{ $value }}</span>
                @endforeach
            </section>
        @endif

        <section class="mt-6 space-y-6">
            @forelse($groupedProducts as $categoryName => $categoryProducts)
                <div class="category-block overflow-hidden rounded-xl border border-slate-200 bg-white">
                    <div class="flex items-center justify-between border-b border-slate-100 bg-slate-50 px-5 py-3">
                        <h2 class="text-sm font-black text-slate-900">{{ $categoryName }}</h2>
                        <span class="text-xs font-bold text-slate-500">{{ $categoryProducts->count() }} product(s)</span>
                    </div>

                    <table class="w-full text-left text-xs">
                        <thead>
                            <tr class="border-b border-slate-100 text-[10px] font-bold uppercase tracking-wider text-slate-500">
                                <th class="px-3 py-2">#</th>
                                <th class="px-3 py-2">Code</th>
                                <th class="px-3 py-2">Product Name</th>
                                <th class="px-3 py-2">Unit</th>
                                <th class="px-3 py-2">Order Units</th>
                                <th class="px-3 py-2 text-center">Status</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-100 font-medium text-slate-800">
                            @foreach($categoryProducts as $index => $product)
                                <tr>
                                    <td class="px-3 py-2 text-slate-400">{{ $index + 1 }}</td>
                                    <td class="px-3 py-2 font-mono text-[11px] font-bold text-slate-600">{{ $product->sku }}</td>
                                    <td class="px-3 py-2 font-bold text-slate-900">{{ $product->name }}</td>
                                    <td class="px-3 py-2 uppercase text-slate-600">{{ $product->unit }}</td>
                                    <td class="px-3 py-2 text-slate-600">
                                        {{ $product->orderUnits->where('is_orderable', true)->pluck('label')->filter()->join(' / ') ?: strtoupper((string) $product->unit) }}
                                    </td>
                                    <td class="px-3 py-2 text-center">
                                        <span class="inline-block rounded px-1.5 py-0.5 text-[10px] font-bold {{ $product->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-500' }}">
                                            {{ $product->is_active ? 'Active' : 'Inactive' }}
                                        </span>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @empty
                <div class="py-12 text-center text-sm font-semibold text-slate-400">
                    No products found matching the selected criteria.
                </div>
            @endforelse
        </section>

        <footer class="mt-8 flex items-center justify-between border-t border-slate-200 pt-4 text-[10px] text-slate-400">
            <span>Green Leaf ERP — Product Management System</span>
            <span>Category-wise product catalog</span>
        </footer>
    </main>
</body>
</html>
