<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Green Leaf - Pending Purchase Bills</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #1f2937;
            margin: 0;
            padding: 20px;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            border-bottom: 2px solid #059669;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #059669;
            font-size: 20px;
            margin: 0 0 4px 0;
            font-weight: bold;
        }
        .header .meta {
            font-size: 11px;
            color: #6b7280;
        }
        .info-grid {
            margin-bottom: 20px;
            background-color: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 10px 14px;
        }
        .info-grid table {
            width: 100%;
            border-collapse: collapse;
        }
        .info-grid td {
            padding: 4px 8px;
            font-size: 11px;
        }
        .info-grid td.label {
            font-weight: bold;
            color: #4b5563;
            width: 120px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        table.data-table th {
            background-color: #f3f4f6;
            color: #374151;
            font-weight: bold;
            text-align: left;
            padding: 8px 10px;
            font-size: 11px;
            border-bottom: 1px solid #d1d5db;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
        table.data-table td {
            padding: 8px 10px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 11px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .badge-warning {
            background-color: #fef3c7;
            color: #92400e;
            padding: 2px 6px;
            border-radius: 4px;
            font-weight: bold;
            font-size: 10px;
        }
        .badge-danger {
            background-color: #fee2e2;
            color: #991b1b;
            padding: 2px 6px;
            border-radius: 4px;
            font-weight: bold;
            font-size: 10px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 12px;
            border-top: 1px solid #e5e7eb;
            font-size: 10px;
            color: #9ca3af;
            text-align: right;
        }
        .summary-box {
            margin-top: 15px;
            background-color: #ecfdf5;
            border: 1px solid #a7f3d0;
            border-radius: 6px;
            padding: 10px 14px;
            font-size: 12px;
            font-weight: bold;
            color: #065f46;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Green Leaf - Pending Purchase Bills</h1>
        <div class="meta">Purchaser Business Day Reconciliation Report</div>
    </div>

    <div class="info-grid">
        <table>
            <tr>
                <td class="label">Warehouse:</td>
                <td>{{ $warehouse ? $warehouse->name : 'All Active Warehouses' }}</td>
                <td class="label">Generated Date:</td>
                <td>{{ $generatedAt }}</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ $generatedBy }}</td>
                <td class="label">Scope:</td>
                <td>Active / Open Business Days with Pending Bills</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 15%;">Business Date</th>
                <th style="width: 15%;">Warehouse</th>
                <th style="width: 30%;">Product</th>
                <th class="text-right" style="width: 15%;">Advance Qty</th>
                <th class="text-right" style="width: 15%;">Matched Qty</th>
                <th class="text-right" style="width: 20%;">Pending Qty</th>
            </tr>
        </thead>
        <tbody>
            @forelse($pendingItems as $index => $item)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td><strong>{{ $item['business_date'] }}</strong></td>
                    <td>{{ $item['warehouse_name'] }}</td>
                    <td>
                        <strong>{{ $item['product_name'] }}</strong>
                        @if(!empty($item['sku']))
                            <div style="font-size: 9px; color: #6b7280;">SKU: {{ $item['sku'] }}</div>
                        @endif
                    </td>
                    <td class="text-right">{{ number_format($item['advance_qty'], 2) }} {{ $item['unit'] }}</td>
                    <td class="text-right">{{ number_format($item['matched_qty'], 2) }} {{ $item['unit'] }}</td>
                    <td class="text-right">
                        <span class="badge-warning">{{ $item['formatted_pending'] }}</span>
                        @if($item['unit_mismatch'])
                            <br><span class="badge-danger">Unit Mismatch</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center" style="padding: 20px; color: #6b7280;">
                        No pending purchase bills found across the selected scope.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary-box">
        Pending Products: {{ count($pendingItems) }}
    </div>

    <div class="footer">
        Generated by Green Leaf ERP &copy; {{ date('Y') }} &bull; Confidential &bull; Page 1
    </div>
</body>
</html>
