<?php

declare(strict_types=1);

namespace App\Exports;

use App\Models\PayrollRun;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;

class PayrollMonthExport implements FromArray, ShouldAutoSize
{
    public function __construct(
        private readonly PayrollRun $payrollRun,
    ) {}

    /**
     * @return array<int, array<int, string|int|float>>
     */
    public function array(): array
    {
        $rows = [
            ['Staff Payroll Month', $this->payrollRun->period_start->format('F Y')],
            ['Status', strtoupper($this->payrollRun->status)],
            ['Generated By', $this->payrollRun->generatedBy?->name ?? 'System'],
            ['Net Amount', (float) $this->payrollRun->net_amount],
            [],
            ['SL No', 'Employee', 'Category', 'Present', 'Half Day', 'Paid Leave', 'Extra Leave', 'Absent', 'Computed Amount', 'Override Amount', 'Final Amount'],
        ];

        foreach ($this->payrollRun->items as $index => $item) {
            $rows[] = [
                $index + 1,
                $item->employee->name,
                $item->category?->name ?? 'Uncategorized',
                (float) $item->present_days,
                (float) $item->half_days,
                (float) $item->paid_leave_days,
                (float) $item->unpaid_leave_days,
                (float) $item->absent_days,
                (float) $item->computed_amount,
                $item->override_amount !== null ? (float) $item->override_amount : 'Auto',
                (float) $item->final_amount,
            ];
        }

        return $rows;
    }
}
