<x-layouts.staff title="Staff Payroll">
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <div>
                <h1 class="text-2xl font-black text-slate-950">Payroll</h1>
                <p class="text-sm font-semibold text-slate-500">Finalize monthly salary snapshots from attendance and category leave rules.</p>
            </div>
            <form method="POST" action="{{ route('admin.staff.payroll.store') }}" class="flex flex-wrap items-center gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
                @csrf
                <label class="block">
                    <span class="text-[11px] font-black uppercase tracking-[0.18em] text-slate-400">Payroll Month</span>
                    <input type="month" name="payroll_month" value="{{ now()->format('Y-m') }}" class="mt-2 rounded-xl border border-slate-200 px-3 py-2 text-sm" required>
                </label>
                <button type="submit" class="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-black text-slate-950">Generate Payroll</button>
            </form>
        </div>

        <div class="space-y-4">
            @foreach($payrollRuns as $run)
                @php($categorySummary = $run->items->groupBy(fn ($item) => $item->category?->name ?? 'Uncategorized'))
                <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                    <div class="flex flex-wrap items-center justify-between gap-3">
                        <div>
                            <h2 class="text-lg font-black text-slate-950">{{ $run->period_start->format('F Y') }}</h2>
                            <p class="text-sm font-semibold text-slate-500">Generated by {{ $run->generatedBy?->name ?? 'System' }}</p>
                            @if($run->journalEntry)
                                <p class="mt-1 text-xs font-semibold text-cyan-700">Posted as expense entry {{ $run->journalEntry->reference }}</p>
                            @endif
                        </div>
                        <div class="text-right">
                            <p class="text-[11px] font-black uppercase tracking-[0.2em] text-slate-400">Net Amount</p>
                            <p class="text-xl font-black text-slate-950">Rs. {{ number_format((float) $run->net_amount, 2) }}</p>
                        </div>
                    </div>

                    <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                        @foreach($categorySummary as $categoryName => $items)
                            <div class="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                                <p class="text-[11px] font-black uppercase tracking-[0.18em] text-slate-400">{{ $categoryName }}</p>
                                <p class="mt-2 text-lg font-black text-slate-950">Rs. {{ number_format((float) $items->sum('final_amount'), 2) }}</p>
                                <p class="mt-1 text-xs font-semibold text-slate-500">{{ $items->count() }} staff in this category</p>
                            </div>
                        @endforeach
                    </div>

                    <div class="mt-4 overflow-x-auto">
                        <table class="min-w-full text-left text-sm">
                            <thead class="text-slate-500">
                                <tr>
                                    <th class="pb-3">Employee</th>
                                    <th class="pb-3">Category</th>
                                    <th class="pb-3">Present</th>
                                    <th class="pb-3">Half</th>
                                    <th class="pb-3">Paid Leave</th>
                                    <th class="pb-3">Excess Leave</th>
                                    <th class="pb-3">Absent</th>
                                    <th class="pb-3">Final</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-slate-100">
                                @foreach($run->items as $item)
                                    <tr>
                                        <td class="py-3 font-bold text-slate-900">{{ $item->employee->name }}</td>
                                        <td class="py-3">{{ $item->category?->name ?? 'Uncategorized' }}</td>
                                        <td class="py-3">{{ $item->present_days }}</td>
                                        <td class="py-3">{{ $item->half_days }}</td>
                                        <td class="py-3">{{ $item->paid_leave_days }}</td>
                                        <td class="py-3">{{ $item->unpaid_leave_days }}</td>
                                        <td class="py-3">{{ $item->absent_days }}</td>
                                        <td class="py-3">Rs. {{ number_format((float) $item->final_amount, 2) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </article>
            @endforeach
        </div>

        <div>{{ $payrollRuns->links() }}</div>
    </div>
</x-layouts.staff>
