<x-layouts.staff title="Staff Payroll">
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <div>
                <h1 class="text-2xl font-black text-slate-950">Payroll</h1>
                <p class="text-sm font-semibold text-slate-500">Show one payroll month at a time, review category totals, override staff amounts when needed, then finalize.</p>
            </div>
        </div>

        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex flex-wrap items-end justify-between gap-3">
                <form method="GET" action="{{ route('admin.staff.payroll.index') }}" class="flex flex-wrap items-end gap-3">
                    <label class="block">
                        <span class="text-[11px] font-black uppercase tracking-[0.18em] text-slate-400">Payroll Month</span>
                        <input type="month" name="payroll_month" value="{{ $selectedPayrollMonth->format('Y-m') }}" class="mt-2 rounded-xl border border-slate-200 px-3 py-2 text-sm" required>
                    </label>
                    <button type="submit" class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-black text-slate-700">Show Month</button>
                </form>

                <div class="flex flex-wrap items-center gap-2">
                    <form method="POST" action="{{ route('admin.staff.payroll.store') }}">
                        @csrf
                        <input type="hidden" name="payroll_month" value="{{ $selectedPayrollMonth->format('Y-m') }}">
                        <button type="submit" class="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-black text-slate-950">Generate Draft Payroll</button>
                    </form>

                    @if($payrollRuns->isNotEmpty())
                        <a href="{{ route('admin.staff.payroll.export.excel', ['payroll_month' => $selectedPayrollMonth->format('Y-m')]) }}" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-black text-emerald-700">Export Excel</a>
                        <a href="{{ route('admin.staff.payroll.export.pdf', ['payroll_month' => $selectedPayrollMonth->format('Y-m')]) }}" target="_blank" class="rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-2 text-sm font-black text-cyan-700">PDF View</a>
                    @else
                        <span class="rounded-xl border border-slate-200 bg-slate-100 px-4 py-2 text-sm font-black text-slate-400">No export until this month has payroll</span>
                    @endif
                </div>
            </div>
        </section>

        <div class="space-y-4">
            @forelse($payrollRuns as $run)
                @php($runSerial = ($payrollRuns->currentPage() - 1) * $payrollRuns->perPage() + $loop->iteration)
                @php($categorySummary = $run->items->groupBy(fn ($item) => $item->category?->name ?? 'Uncategorized'))
                <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                    <div class="flex flex-wrap items-center justify-between gap-3">
                        <div class="flex items-start gap-3">
                            <span class="inline-flex h-10 min-w-10 items-center justify-center rounded-full border border-slate-200 bg-slate-50 px-2 text-[11px] font-black uppercase tracking-[0.14em] text-slate-500">#{{ $runSerial }}</span>
                            <div>
                                <h2 class="text-lg font-black text-slate-950">{{ $run->period_start->format('F Y') }}</h2>
                                <p class="text-sm font-semibold text-slate-500">Generated by {{ $run->generatedBy?->name ?? 'System' }}</p>
                                <div class="mt-2 flex flex-wrap items-center gap-2">
                                    <span class="rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] {{ $run->status === 'draft' ? 'bg-amber-50 text-amber-800 border border-amber-200' : 'bg-emerald-50 text-emerald-800 border border-emerald-200' }}">
                                        {{ $run->status }}
                                    </span>
                                    @if($run->finalizedBy)
                                        <span class="text-xs font-semibold text-slate-500">Finalized by {{ $run->finalizedBy->name }}</span>
                                    @endif
                                </div>
                                @if($run->journalEntry)
                                    <p class="mt-1 text-xs font-semibold text-cyan-700">Posted as expense entry {{ $run->journalEntry->reference }}</p>
                                @endif
                            </div>
                        </div>
                        <div class="text-right">
                            <p class="text-[11px] font-black uppercase tracking-[0.2em] text-slate-400">Net Amount</p>
                            <p class="text-xl font-black text-slate-950">Rs. {{ number_format((float) $run->net_amount, 2) }}</p>
                            @if($run->status === 'draft')
                                <form method="POST" action="{{ route('admin.staff.payroll.finalize', $run) }}" class="mt-3">
                                    @csrf
                                    <input type="hidden" name="payroll_month" value="{{ $selectedPayrollMonth->format('Y-m') }}">
                                    <button type="submit" class="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Finalize Payroll</button>
                                </form>
                            @endif
                        </div>
                    </div>

                    <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                        @foreach($categorySummary as $categoryName => $items)
                            <div class="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                                <p class="text-[11px] font-black uppercase tracking-[0.18em] text-slate-400">{{ $categoryName }}</p>
                                <p class="mt-2 text-lg font-black text-slate-950">Rs. {{ number_format((float) $items->sum('final_amount'), 2) }}</p>
                                <p class="mt-1 text-xs font-semibold text-slate-500">{{ $items->count() }} staff in this category</p>
                            </div>
                        @endforeach
                    </div>

                    <div class="mt-4 overflow-x-auto">
                        <table class="min-w-full text-left text-sm">
                            <thead class="text-slate-500">
                                <tr>
                                    <th class="pb-3">SL No</th>
                                    <th class="pb-3">Employee</th>
                                    <th class="pb-3">Category</th>
                                    <th class="pb-3">Present</th>
                                    <th class="pb-3">Half</th>
                                    <th class="pb-3">Paid Leave</th>
                                    <th class="pb-3">Excess Leave</th>
                                    <th class="pb-3">Absent</th>
                                    <th class="pb-3">Computed</th>
                                    <th class="pb-3">Override</th>
                                    <th class="pb-3">Final</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-slate-100">
                                @foreach($run->items as $item)
                                    <tr>
                                        <td class="py-3 font-black text-slate-500">{{ $loop->iteration }}</td>
                                        <td class="py-3 font-bold text-slate-900">{{ $item->employee->name }}</td>
                                        <td class="py-3">{{ $item->category?->name ?? 'Uncategorized' }}</td>
                                        <td class="py-3">{{ $item->present_days }}</td>
                                        <td class="py-3">{{ $item->half_days }}</td>
                                        <td class="py-3">{{ $item->paid_leave_days }}</td>
                                        <td class="py-3">{{ $item->unpaid_leave_days }}</td>
                                        <td class="py-3">{{ $item->absent_days }}</td>
                                        <td class="py-3">Rs. {{ number_format((float) $item->computed_amount, 2) }}</td>
                                        <td class="py-3">
                                            @if($run->status === 'draft')
                                                <form method="POST" action="{{ route('admin.staff.payroll.items.update', [$run, $item]) }}" class="flex items-center gap-2">
                                                    @csrf
                                                    @method('PATCH')
                                                    <input type="hidden" name="payroll_month" value="{{ $selectedPayrollMonth->format('Y-m') }}">
                                                    <input type="number" step="0.01" min="0" name="override_amount" value="{{ old('override_amount', $item->override_amount) }}" placeholder="Auto" class="w-28 rounded-xl border border-slate-200 px-3 py-2 text-sm">
                                                    <button type="submit" class="rounded-xl bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">Save</button>
                                                </form>
                                            @else
                                                <span class="text-sm font-semibold text-slate-500">{{ $item->override_amount !== null ? 'Rs. '.number_format((float) $item->override_amount, 2) : 'Auto' }}</span>
                                            @endif
                                        </td>
                                        <td class="py-3">Rs. {{ number_format((float) $item->final_amount, 2) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </article>
            @empty
                <div class="rounded-3xl border border-dashed border-slate-200 bg-slate-50 px-5 py-8 text-sm font-semibold text-slate-500">
                    No payroll run found for {{ $selectedPayrollMonth->format('F Y') }}. Generate this month to review or export it.
                </div>
            @endforelse
        </div>

        <div>{{ $payrollRuns->links() }}</div>
    </div>
</x-layouts.staff>
