<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Staff Payroll {{ $selectedPayrollMonth->format('F Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #0f172a;
            margin: 32px;
        }

        h1,
        h2,
        p {
            margin: 0;
        }

        .header {
            margin-bottom: 24px;
        }

        .meta {
            margin-top: 8px;
            color: #475569;
            font-size: 12px;
        }

        .summary {
            display: flex;
            gap: 16px;
            margin: 20px 0 24px;
        }

        .summary-card {
            border: 1px solid #cbd5e1;
            border-radius: 12px;
            padding: 12px 16px;
            min-width: 180px;
        }

        .summary-card span {
            display: block;
            color: #64748b;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.12em;
            margin-bottom: 6px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }

        th,
        td {
            border: 1px solid #cbd5e1;
            padding: 8px 10px;
            text-align: left;
        }

        th {
            background: #e2e8f0;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Staff Payroll</h1>
        <p class="meta">{{ $selectedPayrollMonth->format('F Y') }} payroll review sheet</p>
        <p class="meta">Generated by {{ $payrollRun->generatedBy?->name ?? 'System' }} · Status {{ strtoupper($payrollRun->status) }}</p>
    </div>

    <div class="summary">
        <div class="summary-card">
            <span>Net Amount</span>
            <strong>Rs. {{ number_format((float) $payrollRun->net_amount, 2) }}</strong>
        </div>
        <div class="summary-card">
            <span>Employees</span>
            <strong>{{ $payrollRun->items->count() }}</strong>
        </div>
        <div class="summary-card">
            <span>Finalized By</span>
            <strong>{{ $payrollRun->finalizedBy?->name ?? 'Draft' }}</strong>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>SL No</th>
                <th>Employee</th>
                <th>Category</th>
                <th>Present</th>
                <th>Half Day</th>
                <th>Paid Leave</th>
                <th>Extra Leave</th>
                <th>Absent</th>
                <th>Computed</th>
                <th>Override</th>
                <th>Final</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payrollRun->items as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->employee->name }}</td>
                    <td>{{ $item->category?->name ?? 'Uncategorized' }}</td>
                    <td>{{ $item->present_days }}</td>
                    <td>{{ $item->half_days }}</td>
                    <td>{{ $item->paid_leave_days }}</td>
                    <td>{{ $item->unpaid_leave_days }}</td>
                    <td>{{ $item->absent_days }}</td>
                    <td>Rs. {{ number_format((float) $item->computed_amount, 2) }}</td>
                    <td>{{ $item->override_amount !== null ? 'Rs. '.number_format((float) $item->override_amount, 2) : 'Auto' }}</td>
                    <td>Rs. {{ number_format((float) $item->final_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
