<x-layouts.accounting :title="$invoice->invoice_number">
    <div class="mx-auto max-w-5xl space-y-6">
        <section class="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
                <div>
                    <p class="text-[10px] font-black uppercase tracking-[0.26em] text-slate-400">Settlement Invoice</p>
                    <h1 class="mt-2 text-2xl font-black tracking-tight text-slate-950">{{ $invoice->invoice_number }}</h1>
                    <p class="mt-2 text-sm font-semibold text-slate-600">{{ $shop->name }} • {{ $invoice->period_start->format('d M Y') }} to {{ $invoice->period_end->format('d M Y') }}</p>
                </div>
                <a href="{{ route('admin.accounting.owned-shops.show', ['shop' => $shop, 'date' => $invoice->period_end->format('Y-m-d')]) }}" class="inline-flex h-11 items-center rounded-2xl border border-slate-200 px-4 text-sm font-black text-slate-700 transition hover:bg-slate-50">
                    Back to Shop Accounting
                </a>
            </div>
        </section>

        <section class="grid gap-4 md:grid-cols-4">
            <article class="rounded-[1.35rem] border border-slate-200 bg-white p-5 shadow-sm">
                <p class="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Income</p>
                <p class="mt-2 text-2xl font-black text-slate-950">Rs. {{ number_format((float) $invoice->total_income, 2) }}</p>
            </article>
            <article class="rounded-[1.35rem] border border-slate-200 bg-white p-5 shadow-sm">
                <p class="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Expense</p>
                <p class="mt-2 text-2xl font-black text-slate-950">Rs. {{ number_format((float) $invoice->total_expense, 2) }}</p>
            </article>
            <article class="rounded-[1.35rem] border border-slate-200 bg-white p-5 shadow-sm">
                <p class="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Net Amount</p>
                <p class="mt-2 text-2xl font-black text-slate-950">Rs. {{ number_format((float) $invoice->net_amount, 2) }}</p>
            </article>
            <article class="rounded-[1.35rem] border border-slate-200 bg-white p-5 shadow-sm">
                <p class="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Generated By</p>
                <p class="mt-2 text-lg font-black text-slate-950">{{ $invoice->generatedBy?->name ?? 'Unknown' }}</p>
            </article>
        </section>

        <section class="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm">
            <p class="text-[10px] font-black uppercase tracking-[0.24em] text-slate-400">Partner Share Allocation</p>
            <h2 class="mt-2 text-xl font-black text-slate-950">Ownership split snapshot</h2>

            <div class="mt-6 overflow-x-auto rounded-[1.25rem] border border-slate-200">
                <table class="min-w-full text-left">
                    <thead class="bg-slate-950 text-[10px] font-black uppercase tracking-[0.16em] text-slate-200">
                        <tr>
                            <th class="px-4 py-3">Owner / Partner</th>
                            <th class="px-4 py-3 text-right">Share %</th>
                            <th class="px-4 py-3 text-right">Share Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100 text-sm">
                        @foreach($invoice->splits as $split)
                            <tr>
                                <td class="px-4 py-3 font-black text-slate-950">{{ $split->owner_name_snapshot }}</td>
                                <td class="px-4 py-3 text-right font-semibold text-slate-600">{{ number_format((float) $split->ownership_percent_snapshot, 2) }}%</td>
                                <td class="px-4 py-3 text-right font-black text-slate-950">Rs. {{ number_format((float) $split->share_amount, 2) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            @if(filled($invoice->notes))
                <div class="mt-6 rounded-[1.25rem] border border-slate-200 bg-slate-50 p-4">
                    <p class="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Invoice Note</p>
                    <p class="mt-2 text-sm font-semibold text-slate-700">{{ $invoice->notes }}</p>
                </div>
            @endif
        </section>
    </div>
</x-layouts.accounting>
