<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Selling Price Matrix - {{ \Illuminate\Support\Carbon::parse($targetBusinessDate)->format('d M Y') }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #0f172a; font-size: 11px; margin: 0; padding: 16px; }
        .no-print { display: flex; gap: 8px; margin-bottom: 12px; }
        .no-print button { border: 1px solid #0f172a; background: #fff; border-radius: 6px; padding: 7px 14px; font-weight: 700; cursor: pointer; }
        .header { border-bottom: 2px solid #0f172a; margin-bottom: 12px; padding-bottom: 8px; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        .meta { color: #475569; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        th, td { border: 1px solid #334155; padding: 5px 6px; text-align: left; vertical-align: middle; word-break: break-word; }
        th { background: #e2e8f0; font-size: 10px; text-transform: uppercase; }
        .num { text-align: center; font-family: monospace; font-weight: 700; }
        .changed { color: #dc2626; font-weight: 900; }
        .empty { padding: 18px; text-align: center; color: #64748b; font-weight: 700; }
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
            @page { margin: 10mm; size: landscape; }
        }
    </style>
</head>
<body>
    <div class="no-print">
        <button type="button" onclick="window.print()">Print / Save PDF</button>
        <button type="button" onclick="window.close()">Close</button>
    </div>

    @php
        $title = match ($exportScope) {
            'today' => 'Today Selling Price Matrix',
            'today_changed' => 'Today Changed Selling Prices',
            default => 'Weekly Selling Price Matrix',
        };
    @endphp

    <div class="header">
        <h1>{{ $companyName }} - {{ $title }}</h1>
        <div class="meta">
            Price {{ strtoupper($matrixCategory) }} |
            Date {{ \Illuminate\Support\Carbon::parse($targetBusinessDate)->format('d M Y') }}
            @if ($exportScope === 'week')
                | Week {{ \Illuminate\Support\Carbon::parse($weekStartDate)->format('d M') }} - {{ \Illuminate\Support\Carbon::parse($weekEndDate)->format('d M Y') }}
            @endif
            | Generated by {{ $generatedBy }} at {{ $generatedAt }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 42px;">SL</th>
                <th style="width: 90px;">Code</th>
                <th>Item</th>
                <th style="width: 60px;">Unit</th>
                @if ($exportScope === 'week')
                    @foreach ($matrixDates as $dateStr => $dateInfo)
                        <th class="num">{{ \Illuminate\Support\Carbon::parse($dateStr)->format('d-M') }}</th>
                    @endforeach
                @else
                    <th class="num">{{ \Illuminate\Support\Carbon::parse($targetBusinessDate)->format('d-M') }}</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @forelse ($exportRows as $row)
                <tr>
                    <td class="num">{{ $row['sl_no'] }}</td>
                    <td>{{ $row['sku'] ?: '-' }}</td>
                    <td>{{ $row['name'] }}</td>
                    <td class="num">{{ strtoupper($row['unit']) }}</td>
                    @foreach ($row['prices'] as $priceInfo)
                        <td class="num {{ $priceInfo['changed'] ? 'changed' : '' }}">
                            {{ $priceInfo['price'] !== null ? number_format((float) $priceInfo['price'], 2) : '-' }}
                            @if ($priceInfo['changed'])
                                *
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ $exportScope === 'week' ? count($matrixDates) + 4 : 5 }}" class="empty">No changed prices found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
