<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Categories Catalog — Green Leaf Traders</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        @media print {
            @page {
                size: A4 portrait;
                margin: 8mm 10mm;
            }
            body {
                background-color: #ffffff !important;
                color: #000000 !important;
                padding: 0 !important;
                margin: 0 !important;
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
            }
            .no-print {
                display: none !important;
            }
            .a4-print-card {
                border: 1px solid #cbd5e1 !important;
                box-shadow: none !important;
                max-width: 100% !important;
                width: 100% !important;
                margin: 0 auto !important;
                padding: 1.25rem 1.75rem !important;
            }
            .category-block {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body class="bg-slate-100 py-6 text-slate-950">
    <div class="no-print mx-auto mb-4 flex max-w-4xl items-center justify-between px-4">
        <a href="{{ route('inventory.categories.index') }}"
           class="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-xs font-bold text-slate-700 shadow-sm hover:bg-slate-50 transition-colors">
            <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to Categories
        </a>

        <div class="flex items-center gap-3">
            <span class="text-xs font-bold text-slate-500">
                {{ $categories->count() }} category(ies) selected
            </span>
            <button onclick="window.print()"
                    class="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-2 text-xs font-bold text-white shadow hover:bg-emerald-700 transition-colors">
                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m11.32-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231a1.125 1.125 0 01-1.12-1.227L6.34 18m11.32 0H6.34m0 0h-2.18A1.75 1.75 0 012.41 16.25v-5.5a1.75 1.75 0 011.75-1.75h15.68a1.75 1.75 0 011.75 1.75v5.5a1.75 1.75 0 01-1.75 1.75h-2.18m-11.32 0H6.34" />
                </svg>
                Print / Save PDF
            </button>
        </div>
    </div>

    <div class="a4-print-card mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8 shadow-md">
        {{-- Header Section --}}
        <div class="flex items-start justify-between border-b border-slate-200 pb-5">
            <div>
                <p class="text-[11px] font-black uppercase tracking-[0.25em] text-emerald-700">Green Leaf Traders</p>
                <h1 class="mt-1 text-2xl font-black tracking-tight text-slate-900">Product Categories Catalog</h1>
                <p class="mt-1 text-xs font-semibold text-slate-500">Official Product & Category Inventory Summary</p>
            </div>
            <div class="text-right">
                <p class="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Generated Date</p>
                <p class="mt-1 text-xs font-bold text-slate-800">{{ now()->format('d M Y, h:i A') }}</p>
                <p class="mt-1 text-[11px] font-semibold text-slate-500">Generated by: {{ auth()->user()?->name ?? 'System' }}</p>
            </div>
        </div>

        {{-- Summary Stats Bar --}}
        <div class="mt-4 grid grid-cols-3 gap-4 rounded-xl border border-slate-100 bg-slate-50 p-4">
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Total Categories</p>
                <p class="mt-0.5 text-lg font-black text-slate-900">{{ $categories->count() }}</p>
            </div>
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Total Products</p>
                <p class="mt-0.5 text-lg font-black text-emerald-700">{{ number_format($totalProducts) }}</p>
            </div>
            <div>
                <p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Active Categories</p>
                <p class="mt-0.5 text-lg font-black text-slate-900">{{ $categories->where('is_active', true)->count() }} / {{ $categories->count() }}</p>
            </div>
        </div>

        {{-- Categories Content --}}
        <div class="mt-6 space-y-6">
            @forelse($categories as $category)
                <div class="category-block rounded-xl border border-slate-200 p-5 bg-white">
                    <div class="flex items-center justify-between border-b border-slate-100 pb-3">
                        <div class="flex items-center gap-3">
                            <h2 class="text-base font-black text-slate-900">{{ $category->name }}</h2>
                            <span class="inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-[11px] font-bold {{ $category->is_active ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' : 'bg-slate-100 text-slate-500' }}">
                                {{ $category->is_active ? 'Active' : 'Inactive' }}
                            </span>
                        </div>
                        <span class="text-xs font-bold text-slate-500">
                            {{ $category->products->count() }} product(s)
                        </span>
                    </div>

                    @if($category->description)
                        <p class="mt-2 text-xs text-slate-600 italic">{{ $category->description }}</p>
                    @endif

                    @if($category->products->isNotEmpty())
                        <div class="mt-3 overflow-hidden rounded-lg border border-slate-100">
                            <table class="w-full text-left text-xs">
                                <thead>
                                    <tr class="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-500 border-b border-slate-100">
                                        <th class="px-3 py-2">#</th>
                                        <th class="px-3 py-2">Product Name</th>
                                        <th class="px-3 py-2">SKU</th>
                                        <th class="px-3 py-2">Unit</th>
                                        <th class="px-3 py-2 text-right">Base Price</th>
                                        <th class="px-3 py-2 text-center">Status</th>
                                    </tr>
                                </thead>
                                <tbody class="divide-y divide-slate-100 font-medium text-slate-800">
                                    @foreach($category->products as $index => $product)
                                        <tr class="hover:bg-slate-50/50">
                                            <td class="px-3 py-2 text-slate-400">{{ $index + 1 }}</td>
                                            <td class="px-3 py-2 font-bold text-slate-900">{{ $product->name }}</td>
                                            <td class="px-3 py-2 font-mono text-[11px] text-slate-600">{{ $product->sku ?: '—' }}</td>
                                            <td class="px-3 py-2 uppercase text-slate-600">{{ $product->unit }}</td>
                                            <td class="px-3 py-2 text-right font-bold text-slate-900">
                                                Rs. {{ number_format((float) $product->base_price, 2) }}
                                            </td>
                                            <td class="px-3 py-2 text-center">
                                                <span class="inline-block rounded px-1.5 py-0.5 text-[10px] font-bold {{ $product->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-500' }}">
                                                    {{ $product->is_active ? 'Active' : 'Inactive' }}
                                                </span>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <p class="mt-3 text-xs text-slate-400 italic bg-slate-50 p-3 rounded-lg text-center">
                            No products assigned to this category.
                        </p>
                    @endif
                </div>
            @empty
                <div class="py-12 text-center text-slate-400">
                    <p class="text-sm font-semibold">No categories found matching the selected criteria.</p>
                </div>
            @endforelse
        </div>

        {{-- Footer --}}
        <div class="mt-8 border-t border-slate-200 pt-4 flex items-center justify-between text-[10px] text-slate-400">
            <span>Green Leaf ERP — Product Management System</span>
            <span>Page 1 of 1</span>
        </div>
    </div>
</body>
</html>
