@php
    $context = ['period' => $filters['period'], 'produce_type' => $filters['warehouse_code'] === 'VEG-WH' ? 'vegetables' : ($filters['warehouse_code'] === 'FRT-WH' ? 'fruits' : 'all')];
    if (in_array($filters['period'], ['custom', 'between', 'range'], true)) { $context += ['start_date' => $filters['start_date'], 'end_date' => $filters['end_date']]; }
    $detailUrl = match($section) { 'purchasers' => route('admin.cashbook.finance.purchase.purchasers.show', ['purchaser' => $row->purchaser_public_uuid] + $context), 'vendors' => route('admin.cashbook.finance.purchase.vendors.show', ['supplier' => $row->supplier_public_uuid] + $context), 'categories' => route('admin.cashbook.finance.purchase.categories.show', ['category' => $row->category_id] + $context), default => route('purchasing.invoices.show', $row->invoice_public_uuid) };
    $title = $section === 'purchasers' ? ($row->purchaser_name ?: 'Unassigned') : ($section === 'vendors' ? ($row->supplier_name ?: 'Unknown') : ($section === 'categories' ? ($row->category_name ?: 'Uncategorized') : ($row->invoice_number ?: 'Invoice')));
@endphp
@if($mobile)
    <article class="space-y-3 p-4 text-xs"><div class="flex items-start justify-between gap-3"><a href="{{ $detailUrl }}" class="font-black text-emerald-700">{{ $title }}</a><strong class="font-mono">₹{{ number_format((float) $row->total_purchase, 2) }}</strong></div><div class="grid grid-cols-2 gap-2 text-slate-600">@if($section === 'invoices')<span>{{ $row->business_date }}</span><span class="text-right uppercase">{{ $row->payment_class }}</span><span>{{ $row->supplier_name }}</span><span class="text-right">{{ $row->purchaser_name }}</span><span class="col-span-2">{{ $row->categories }}</span>@else<span>Cash ₹{{ number_format((float) $row->cash_purchase, 2) }}</span><span class="text-right">Credit ₹{{ number_format((float) $row->credit_purchase, 2) }}</span><span>Invoices {{ number_format((int) $row->invoice_count) }}</span>@endif</div><a href="{{ $detailUrl }}" class="inline-flex rounded-lg border border-slate-300 px-3 py-2 font-black text-slate-700">View</a></article>
@elseif($section === 'purchasers')
    <tr><td class="p-3 font-bold"><a class="text-emerald-700 hover:underline" href="{{ $detailUrl }}">{{ $title }}</a></td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->total_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->cash_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->credit_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->funding, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->balance, 2) }}</td><td class="p-3 text-right">{{ $row->invoice_count }}</td><td class="p-3"><a href="{{ $detailUrl }}" class="font-black text-emerald-700">View</a></td></tr>
@elseif($section === 'vendors')
    @php $allTags = collect(explode(',', (string) $row->category_tags))->filter(); $tags = $allTags->take(3); @endphp
    <tr><td class="p-3 font-bold"><a class="text-emerald-700 hover:underline" href="{{ $detailUrl }}">{{ $title }}</a></td><td class="p-3"><div class="flex flex-wrap gap-1">@foreach($tags as $tag)<span class="rounded bg-slate-100 px-2 py-1">{{ explode('|', $tag, 2)[1] ?? $tag }}</span>@endforeach @if($allTags->count() > 3)<span class="rounded bg-slate-900 px-2 py-1 text-white">+{{ $allTags->count() - 3 }}</span>@endif</div></td><td class="p-3 text-right">{{ $row->invoice_count }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->cash_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->credit_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->outstanding, 2) }}</td><td class="p-3 text-right font-mono font-bold">₹{{ number_format((float) $row->total_purchase, 2) }}</td><td class="p-3"><a href="{{ $detailUrl }}" class="font-black text-emerald-700">View</a></td></tr>
@elseif($section === 'categories')
    <tr><td class="p-3 font-bold"><a class="text-emerald-700 hover:underline" href="{{ $detailUrl }}">{{ $title }}</a></td><td class="p-3 text-right font-mono font-bold">₹{{ number_format((float) $row->total_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->cash_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->credit_purchase, 2) }}</td><td class="p-3 text-right">{{ $row->vendor_count }}</td><td class="p-3 text-right">{{ $row->purchaser_count }}</td><td class="p-3 text-right">{{ $row->invoice_count }}</td></tr>
@else
    <tr><td class="p-3 font-mono">{{ $row->business_date }}</td><td class="p-3 font-bold"><a class="text-emerald-700 hover:underline" href="{{ $detailUrl }}">{{ $title }}</a></td><td class="p-3">{{ $row->supplier_name }}</td><td class="p-3">{{ $row->purchaser_name }}</td><td class="p-3">{{ $row->categories }}</td><td class="p-3 uppercase">{{ $row->payment_class }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->total_purchase, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->paid_amount, 2) }}</td><td class="p-3 text-right font-mono">₹{{ number_format((float) $row->outstanding, 2) }}</td><td class="p-3"><a href="{{ $detailUrl }}" class="font-black text-emerald-700">View</a></td></tr>
@endif
