<x-layouts.admin title="Empty Warehouse">
    <div class="mx-auto max-w-3xl space-y-6">
        <div class="rounded-3xl border border-rose-200 bg-rose-50 p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-[.18em] text-rose-700">Danger zone</p><h1 class="mt-2 text-2xl font-black text-rose-950">Empty Warehouse</h1><p class="mt-2 text-sm font-semibold text-rose-900">This will set every current inventory stock to zero. Products, orders, purchases, deliveries and history are not deleted.</p><p class="mt-4 text-sm font-black text-rose-950">{{ number_format($recordCount) }} inventory products will be cleared.</p></div>
        @if($activeProcess)<div class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-bold text-amber-900">An empty-inventory process is already running. Its progress is shown below.</div>@else
        <form method="POST" action="{{ route('admin.inventory-empty.store') }}" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<label class="block text-sm font-black text-slate-900">Type <span class="font-mono">EMPTY WAREHOUSE</span> to confirm</label><input name="confirmation" required autocomplete="off" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-bold focus:border-rose-500 focus:outline-none focus:ring-2 focus:ring-rose-500/20"><button class="mt-5 rounded-xl bg-rose-700 px-5 py-3 text-sm font-black text-white hover:bg-rose-800">Empty All Inventory</button></form>@endif
        @if($activeProcess || request('process'))<div id="progress" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-[.18em] text-slate-500">Emptying Warehouse Inventory</p><p id="status" class="mt-2 text-xl font-black text-slate-950">Starting…</p><p id="counts" class="mt-3 text-sm font-bold text-slate-600"></p><p id="current" class="mt-1 text-sm font-semibold text-slate-500"></p><div class="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div id="bar" class="h-full bg-rose-600 transition-all" style="width:0%"></div></div><p id="percent" class="mt-2 text-right text-sm font-black text-rose-700">0%</p></div>
        <script>const url=@json(route('admin.inventory-empty.progress',['process'=>$activeProcess?->id ?? request('process')]));const poll=async()=>{const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)return;const d=await r.json();document.querySelector('#status').textContent=d.status;document.querySelector('#counts').textContent=`Processed: ${d.processed} / ${d.total} · Successful: ${d.successful} · Failed: ${d.failed}`;document.querySelector('#current').textContent=d.current_product?`Current product: ${d.current_product}`:'';document.querySelector('#bar').style.width=d.percent+'%';document.querySelector('#percent').textContent=d.percent+'%';if(['pending','running'].includes(d.status))setTimeout(poll,1500)};poll()</script>@endif
    </div>
</x-layouts.admin>
